PUT  http://localhost:3000/api/games/26
Content-Type: application/json
{
 "name": "elden ring",
 "description": "An epic fantasy action-RPG.",
 "quantity": 3,
 "url": "https://example.com/eldenring.jpg",
 "price": 90,
 "console": "playstation",
 "id": 28
}