PUT  http://localhost:3000/consoles/playstation
Content-Type: application/json
{
  "name": "Elden Ring",
  "quanty": "3",
  "description": "An action RPG game developed by FromSoftware and published by Bandai Namco Entertainment.",
  "url": "https://example.com/eldenring.jpg",
  "price": 19.99,
}